### PR TITLE
Optional deep merge on updates

### PR DESCRIPTION
**Pull request by chadwithuhc**
Howdy!

A deep merge [forcefully happens](https://github.com/js-data/js-data-firebase/blob/master/src/index.js#L438) when updating items in Firebase. This PR will add the option to disable it by passing in an option `deepMerge` set to `false`. Since the default behavior was deep merge for so long I wouldn't want to change the default for anyone who relies on it, thus a new option was born.

Example usage:
```js
// from a record instance
entry.save({ deepMerge: false })

// note: save calls create or update automatically
```

- [x] - `npm test` succeeds
- [ ] - Code coverage does not decrease (if any source code was changed)
- [ ] - Appropriate JSDoc comments were updated in source code (if applicable)
- [ ] - Appropriate changes to js-data.io docs have been suggested ("Suggest Edits" button)

### CODE REVIEW

**Comment by crobinson42** [comment]
@chadwithuhc thx - i'll merge this but can you please add the new option to the js-doc comment around here: https://github.com/js-data/js-data-firebase/blob/master/src/index.js#L85

**Comment by chadwithuhc** [comment]
Added the doc comment with the `_update()` method since it's not passed in with the main adapter settings. let me know if you see anything else!

**Comment by crobinson42** [comment]
published 3.2.1

**Comment by chadwithuhc** [comment]
thanks for your help cory!

**Pull request merged**
